# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vision-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jarvisapiregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bdbf0b7c241045fbb55b278074844883 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_170b482562cf47029a124bf48d6e94d8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jarvisapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bdbf0b7c241045fbb55b278074844883 }}/jarvisapiregistry/vision-frontend-cp/production:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
         API_ENDPOINT=${{ secrets.API_ENDPOINT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vision-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30a727aaf730468a8b060a8a1af2fbac }}
        images: 'jarvisapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bdbf0b7c241045fbb55b278074844883 }}/jarvisapiregistry/vision-frontend-cp/production:${{ github.sha }}'
